-- ====================================================================
-- SCHEMA MIGRATIONS (Safe for clean and existing databases)
-- ====================================================================

-- 1. Sale Orders
ALTER TABLE IF EXISTS sale_orders ADD COLUMN IF NOT EXISTS customer_name VARCHAR(200);
ALTER TABLE IF EXISTS sale_orders ADD COLUMN IF NOT EXISTS customer_phone VARCHAR(30);
ALTER TABLE IF EXISTS sale_orders ADD COLUMN IF NOT EXISTS shipping_address TEXT;
ALTER TABLE IF EXISTS sale_orders ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE IF EXISTS sale_orders ADD COLUMN IF NOT EXISTS order_origin VARCHAR(50) DEFAULT 'ONLINE';
ALTER TABLE IF EXISTS sale_orders ADD COLUMN IF NOT EXISTS payment_status VARCHAR(50) DEFAULT 'UNPAID';

-- 2. Sale Order Details
ALTER TABLE IF EXISTS sale_order_details ADD COLUMN IF NOT EXISTS unit_price NUMERIC(18, 2);
ALTER TABLE IF EXISTS sale_order_details ADD COLUMN IF NOT EXISTS discount_amount NUMERIC(18, 2) DEFAULT 0;
ALTER TABLE IF EXISTS sale_order_details ADD COLUMN IF NOT EXISTS tax_amount NUMERIC(18, 2) DEFAULT 0;
ALTER TABLE IF EXISTS sale_order_details ADD COLUMN IF NOT EXISTS total_amount NUMERIC(18, 2);
ALTER TABLE IF EXISTS sale_order_details ADD COLUMN IF NOT EXISTS order_id BIGINT;
ALTER TABLE IF EXISTS sale_order_details ADD COLUMN IF NOT EXISTS sale_order_id BIGINT;

-- 3. Delivery Assignment Histories
ALTER TABLE IF EXISTS delivery_assignment_histories ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE IF EXISTS delivery_assignment_histories ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);
ALTER TABLE IF EXISTS delivery_assignment_histories ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;
ALTER TABLE IF EXISTS delivery_assignment_histories ADD COLUMN IF NOT EXISTS deleted_by VARCHAR(255);
ALTER TABLE IF EXISTS delivery_assignment_histories ADD COLUMN IF NOT EXISTS is_locked BOOLEAN DEFAULT false;
ALTER TABLE IF EXISTS delivery_assignment_histories ADD COLUMN IF NOT EXISTS trace_id VARCHAR(255);
ALTER TABLE IF EXISTS delivery_assignment_histories ADD COLUMN IF NOT EXISTS version INTEGER DEFAULT 0;
ALTER TABLE IF EXISTS delivery_assignment_histories ADD COLUMN IF NOT EXISTS tenant_id BIGINT;

-- 4. Product Variants & Stock Ledgers
ALTER TABLE IF EXISTS product_variants ADD COLUMN IF NOT EXISTS attribute_signature VARCHAR(500);
ALTER TABLE IF EXISTS stock_ledgers ADD COLUMN IF NOT EXISTS product_variant_id BIGINT;

-- 5. Purchase Orders
ALTER TABLE IF EXISTS purchase_orders ADD COLUMN IF NOT EXISTS payment_status VARCHAR(50) DEFAULT 'UNPAID';
ALTER TABLE IF EXISTS purchase_orders ADD COLUMN IF NOT EXISTS advance_amount NUMERIC(18, 2) DEFAULT 0;

-- 6. Customers
ALTER TABLE IF EXISTS customers ADD COLUMN IF NOT EXISTS dob DATE;
ALTER TABLE IF EXISTS customers ADD COLUMN IF NOT EXISTS gender VARCHAR(10);
ALTER TABLE IF EXISTS customers ADD COLUMN IF NOT EXISTS tax_code VARCHAR(50);
ALTER TABLE IF EXISTS customers ADD COLUMN IF NOT EXISTS note TEXT;
ALTER TABLE IF EXISTS customers ADD COLUMN IF NOT EXISTS group_id BIGINT;
ALTER TABLE IF EXISTS customers ADD COLUMN IF NOT EXISTS area_id BIGINT;

-- 7. Debt Ledgers
ALTER TABLE IF EXISTS debt_ledgers ADD COLUMN IF NOT EXISTS entity_name VARCHAR(200);
ALTER TABLE IF EXISTS debt_ledgers ADD COLUMN IF NOT EXISTS entity_type VARCHAR(30);
ALTER TABLE IF EXISTS debt_ledgers ADD COLUMN IF NOT EXISTS due_date TIMESTAMP;
ALTER TABLE IF EXISTS debt_ledgers ADD COLUMN IF NOT EXISTS status VARCHAR(30);
ALTER TABLE IF EXISTS debt_ledgers ADD COLUMN IF NOT EXISTS last_payment_date TIMESTAMP;
ALTER TABLE IF EXISTS debt_ledgers ADD COLUMN IF NOT EXISTS account_manager VARCHAR(100);

-- 8. Shipping Carriers
ALTER TABLE IF EXISTS shipping_carriers ADD COLUMN IF NOT EXISTS email VARCHAR(150);
ALTER TABLE IF EXISTS shipping_carriers ADD COLUMN IF NOT EXISTS phone VARCHAR(50);
ALTER TABLE IF EXISTS shipping_carriers ADD COLUMN IF NOT EXISTS website VARCHAR(255);
ALTER TABLE IF EXISTS shipping_carriers ADD COLUMN IF NOT EXISTS address VARCHAR(255);
ALTER TABLE IF EXISTS shipping_carriers ADD COLUMN IF NOT EXISTS contact_person VARCHAR(150);
ALTER TABLE IF EXISTS shipping_carriers ADD COLUMN IF NOT EXISTS notes TEXT;

-- 9. Users
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS avatar TEXT;

-- 10. Finance & Bank Accounts
ALTER TABLE IF EXISTS bank_accounts ADD COLUMN IF NOT EXISTS swift_bic VARCHAR(50);
ALTER TABLE IF EXISTS bank_accounts ADD COLUMN IF NOT EXISTS currency VARCHAR(10) DEFAULT 'VND';
ALTER TABLE IF EXISTS bank_accounts ADD COLUMN IF NOT EXISTS current_balance NUMERIC(18, 2) DEFAULT 0;
ALTER TABLE IF EXISTS bank_accounts ADD COLUMN IF NOT EXISTS available_working_capital NUMERIC(18, 2) DEFAULT 0;
ALTER TABLE IF EXISTS bank_accounts ADD COLUMN IF NOT EXISTS account_type VARCHAR(50) DEFAULT 'PRIMARY_OPERATING';
ALTER TABLE IF EXISTS bank_accounts ADD COLUMN IF NOT EXISTS opened_date VARCHAR(20);
ALTER TABLE IF EXISTS bank_accounts ADD COLUMN IF NOT EXISTS status VARCHAR(30) DEFAULT 'ACTIVE';
ALTER TABLE IF EXISTS bank_accounts ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true;

ALTER TABLE IF EXISTS fund_balances ADD COLUMN IF NOT EXISTS branch_name VARCHAR(150);
ALTER TABLE IF EXISTS fund_balances ADD COLUMN IF NOT EXISTS manager_name VARCHAR(100);

ALTER TABLE IF EXISTS transaction_reasons ADD COLUMN IF NOT EXISTS accounting_code VARCHAR(30);
ALTER TABLE IF EXISTS transaction_reasons ADD COLUMN IF NOT EXISTS description VARCHAR(255);

ALTER TABLE IF EXISTS fixed_assets ADD COLUMN IF NOT EXISTS category VARCHAR(100);
ALTER TABLE IF EXISTS fixed_assets ADD COLUMN IF NOT EXISTS accumulated_depreciation NUMERIC(18, 2) DEFAULT 0;
ALTER TABLE IF EXISTS fixed_assets ADD COLUMN IF NOT EXISTS useful_life_months INTEGER DEFAULT 36;
ALTER TABLE IF EXISTS fixed_assets ADD COLUMN IF NOT EXISTS status VARCHAR(30) DEFAULT 'ACTIVE';

-- 11. Banners Column Alignment
ALTER TABLE IF EXISTS banners ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS banners ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS banners ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true;
ALTER TABLE IF EXISTS banners ADD COLUMN IF NOT EXISTS sort_order INTEGER DEFAULT 0;
ALTER TABLE IF EXISTS banners ADD COLUMN IF NOT EXISTS image_url TEXT;
ALTER TABLE IF EXISTS banners ADD COLUMN IF NOT EXISTS link_url VARCHAR(255);
ALTER TABLE IF EXISTS banners ADD COLUMN IF NOT EXISTS valid_from TIMESTAMP;
ALTER TABLE IF EXISTS banners ADD COLUMN IF NOT EXISTS valid_until TIMESTAMP;


