spring.application.name=storemanager
spring.datasource.url=jdbc:postgresql://localhost:5432/smart_retail_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8080
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Ho_Chi_Minh
spring.jpa.hibernate.ddl-auto=update
spring.jackson.time-zone=Asia/Ho_Chi_Minh
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
logging.level.com.smartretail.backend=DEBUG
logging.level.org.springframework.security=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
app.jwtSecret=SmartRetailProject2026_SecureKeyForJWT_MustBeAtLeast64CharactersLong_For_HS512_Security
app.jwtExpirationInMs=86400000
jwt.secret=SmartRetailProject2026_SecureKeyForJWT_MustBeAtLeast64CharactersLong_For_HS512_Security
jwt.expiration=86400000
jwt.access-token-expiration=3600000
jwt.refresh-token-expiration=604800000
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=smartretail.contact@gmail.com
spring.mail.password=vpuvrueaygzbigtb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=3000
spring.mail.properties.mail.smtp.writetimeout=5000
app.base.url=http://localhost:8080
app.registration.token.expiration=86400000
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false
cloudinary.cloud-name=ddjd3bkh2
cloudinary.api-key=594541298539529
cloudinary.api-secret=9RZap99fEpt7mm_jf7z0FZMNUik
google.sheets.enabled=true
google.sheets.applicationName=SmartRetail
google.sheets.spreadsheet.id=1kqIwL_PL_cEkouE9EQiIuXu-fDebcrRd2I_w1TnDyc8
google.drive.folder.id=D:\\Backend9\\src\\main\\resources\\gg-sheet-489707-0d444187388e.json
google.credentials.file.path=classpath:gg-sheet-489707-0d444187388e.json

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration